### ISSUE TITLE
Warning: Calling 'depends_on ... => :run' is deprecated!

### ISSUE THREAD

**Issue by calvins** [dpo/homebrew-openblas#55]
Today 4/10/2018, I received the following warning after running brew update.

_**Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/dpo/homebrew-openblas/octave.rb:48:in `<class:Octave>'
Please report this to the dpo/openblas tap!**_

I hope this is the right place to report this and apologize if it is not.

**Comment by schoeps** [comment]
Thanks! You are at the right spot. I will fix this in the next update. That might take a few days... I am waiting for the first release candidate of octave 4.4.

**Comment by dpo** [comment]
@schoeps Can I simply remove `:run` for now, even if it's just a temporary fix? Currently, all other builds fail because 3 formulae still have `:run` dependencies.

**Comment by schoeps** [comment]
yes sure. I have a bigger changeset in the pipeline (#54) but that may need some time.
