### ISSUE TITLE
i tried installing ipopt in my mac facing the issue:`mumps` is trying to use 'depends_on :mpi' but it should be "open-mpi"

### ISSUE THREAD

**Issue by SarveshShukla23** [dpo/homebrew-openblas#58]
To help us debug your issue please explain:

What you were trying to do (and why): i was trying to install ipopt for my udacity Mpc project.
What happened (include command output):while install mumps is trying to use 'depends_on :mpi' but it should be "open-mpi";
What you expected to happen: download ipopt on my mac
Step-by-step reproduction instructions (by running brew install commands):
i tried installing brew using :
brew install dpo/openblas/ipopt

Error received : 
This is the error i am getting in mac.
Calling 'depends_on :mpi' is disabled!
Use 'depends_on "open-mpi"' instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mumps.rb:16:in `class:Mumps'
Please report this to the homebrew/core tap!
Or, even better, submit a PR to fix it!

**Comment by dpo** [comment]
Something is off with your local install of Homebrew. This is not the homebre/core tap, and homebrew/core doesn't provide ipopt. You might be using a (very) outdated version. Try `brew update`.

**Comment by dpo** [comment]
I'm going to close this. Please feel free to reopen or open a new issue if difficulties persist.
