### ISSUE TITLE
mumps mpi install option

### ISSUE THREAD

**Issue by jeguzzi** [dpo/homebrew-openblas#62]
The `--without-mpi` option of mumps in https://github.com/dpo/homebrew-openblas/blob/master/mumps.rb#L7 is wrong.

`brew info mumps` returns

```
==> Options
...
--without-mpi
	build with MPI
```

instead of

```
==> Options
...
--with-mpi
	build with MPI
```

as this option *enable* MPI.

**Comment by dpo** [comment]
Thanks! Feel free to send a pull request to fix it.
