### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by apjanke** [dpo/homebrew-openblas#73]
Could you add a LICENSE file to the repo indicating what license these formula files are available under?

Since they're mostly derivatives of the core Homebrew formulae, which are BSD 2-clause, this should probably be BSD 2-clause too, yes?

I don't mean to be a nag; I'm asking because I'd like to grab and derive from a couple of these formulae myself, and am wondering what license I should publish them under.

**Comment by dpo** [comment]
They're actually derivatives of the late homebrew/science formulae. Did those ever have a licence?

**Comment by apjanke** [comment]
Yeah, I think those were BSD 2-Clause, too. You can still see [the LICENSE file in the deprecated repo](https://github.com/Homebrew/homebrew-science/blob/2a5d656871d6822334fcb48dddfa79a23f6e86c6/LICENSE), and the text matches the BSD 2-Clause license to my eyes.

**Comment by apjanke** [comment]
Thank you!
