### ISSUE TITLE
Error installing Octave

### ISSUE THREAD

**Issue by aSapien** [dpo/homebrew-openblas#79]
Hi,

I'm really struggling to get Octave (with gui) working on my machine, running a 2017 MacBook Pro with High Sierra 10.13.6.

I started with the guide at [octave-on-macos-with-gui](http://www.schoeps.org/home/2017/10/octave-on-macos-with-gui/)
Since it produced errors related to `QButton...`, I found issue #68 and followed to #67 where I tried the instructions in [the comment](https://github.com/dpo/homebrew-openblas/issues/67#issuecomment-394166027), but unfortunately to no avail. 
I've also tried to execute the installs one-by-one as described in a [later comment](https://github.com/dpo/homebrew-openblas/issues/67#issuecomment-407303067) but that yields the same results for me. 

At some point I also tried to modify the `octave.rb` file and attempt an install, as described in a [an earlier issue](https://github.com/dpo/homebrew-openblas/issues/59#issuecomment-383277345) but that didn't work either.

If it's of any help, I can say that I have version 1.16 `aclocal` installed because running `aclocal-1.16 --version` from home dir returns the version information. Running `aclocal-1.15 --version` produces an error.

The logs gist from `brew gist-logs octave` is [here](https://gist.github.com/aSapien/ba68667f074c011a7b99273fd8f5e8c6)

Ane help is greatly appreciated!

Thanks,
Dima

**Comment by aSapien** [comment]
I believe this issue is related to (or, a duplicate of) issue #67. Although, unlike the issue title, since running `curl https://raw.githubusercontent.com/schoeps/homebrew-openblas/master/octave.rb -o /usr/local/Homebrew/Library/Taps/dpo/homebrew-openblas/octave.rb` The attempts should install Octave 4.4

**Comment by schoeps** [comment]
I should probably update the explanation on the website. I was recently more focussing on http://octave-app.org (where you can get a preconpiled binary if you like). However, the steps from #67 should be still correct and give you a working Octave 4.4:

```
# get newest formula
brew update
brew upgrade
# make sure that dependencies are compiled from dpo's repository
brew reinstall openblas
brew reinstall dpo/homebrew-openblas/arpack
brew reinstall dpo/homebrew-openblas/qrupdate
brew reinstall dpo/homebrew-openblas/suite-sparse
brew reinstall dpo/homebrew-openblas/sundials27
# install the new formula from my pull request
curl https://raw.githubusercontent.com/schoeps/homebrew-openblas/master/octave.rb -o /usr/local/Homebrew/Library/Taps/dpo/homebrew-openblas/octave.rb
#compile octave
brew install dpo/homebrew-openblas/octave --verbose --with-qt --with-java
```

**Comment by aSapien** [comment]
@schoeps Thank you for your response. As a matter of fact, during my quest for a solution, several hours ago I stumbled upon [this repo](https://github.com/schoeps/octave_installer) on your github, which led me to [octave-app.org](octave-app.org).

I had used the instructions as follows:

```sh
brew tap octave-app/octave-app
brew cask install octave-app
```

It worked perfectly, and I will tell my colleagues to use the same instructions.

You can close this ticket as resolved, your help is much appreciated.

Cheers,
Dima
