### ISSUE TITLE
Error installing dpo/openblas/scalapack on MacOS

### ISSUE THREAD

**Issue by seokhojeong** [dpo/homebrew-openblas#86]
Hello,

I was trying to install mumps on my Mac. While scalapack was being installed in the process, I am getting the following error message. Any idea what went wrong? Many thanks.

==> Installing dpo/openblas/mumps dependency: dpo/openblas/scalapack
==> Downloading http://www.netlib.org/scalapack/scalapack-2.0.2.tgz
######################################################################## 100.0%
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/scalapack/2.0.2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_
==> make all
Last 15 lines from /Users/sjeong/Library/Logs/Homebrew/scalapack/02.make:
      ierr=MPI_Type_struct(i, len, disp, dtypes, &MyType);
           ^
/usr/local/Cellar/open-mpi/4.0.2/include/mpi.h:2850:31: note: expanded from macro 'MPI_Type_struct'
make[2]: *** [CMakeFiles/scalapack.dir/BLACS/SRC/dgamx2d_.c.o] Error 1
#define MPI_Type_struct(...)  THIS_SYMBOL_WAS_REMOVED_IN_MPI30(MPI_Type_struct, MPI_Type_create_struct)
                              ^
make[2]: *** Waiting for unfinished jobs....
/usr/local/Cellar/open-mpi/4.0.2/include/mpi.h:322:57: note: expanded from macro 'THIS_SYMBOL_WAS_REMOVED_IN_MPI30'
make[2]: *** [CMakeFiles/scalapack.dir/BLACS/SRC/igamx2d_.c.o] Error 1
#define THIS_SYMBOL_WAS_REMOVED_IN_MPI30(func, newfunc) _Static_assert(0, #func " was removed in MPI-3.0.  Use " #newfunc " instead.")
                                                        ^
1 error generated.
make[2]: *** [CMakeFiles/scalapack.dir/BLACS/SRC/sgamx2d_.c.o] Error 1
make[1]: *** [CMakeFiles/scalapack.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/dpo/homebrew-openblas/issues

These open issues may also help:
enhancement: much faster build via modern CMake for Scalapack and Mumps https://github.com/dpo/homebrew-openblas/issues/84

**Comment by dpo** [comment]
This repository isn't maintained anymore. Please use https://github.com/brewsci/homebrew-num.
